name: Build and Release Binaries

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    name: Build and Release Binaries
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Only run on pushes to main
    permissions:
      contents: write # Required to create a release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Get short SHA
        id: vars
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        shell: bash

      - name: Install NPM dependencies
        run: npm install ci

      - name: Build Linux Binary
        run: bun build worker/worker.ts --compile --target=bun-linux-x64-modern --outfile dist/friendlai-${{ env.sha }}-linux

      - name: Build Windows Binary
        run: bun build worker/worker.ts --compile --target=bun-windows-x64-modern --outfile dist/friendlai-${{ env.sha }}-windows.exe

      - name: Build macOS Binary
        run: bun build worker/worker.ts --compile --target=bun-darwin-arm64 --outfile dist/friendlai-${{ env.sha }}-macos

      - name: Create JSON file with filenames, SHA, and date
        run: |
          echo '{
            "linux": "friendlai-${{ env.sha }}-linux",
            "windows": "friendlai-${{ env.sha }}-windows.exe",
            "macos": "friendlai-${{ env.sha }}-macos",
            "sha": "${{ env.sha }}",
            "date": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          }' > dist/release-info.json
        shell: bash

      - name: List built files (for debugging)
        run: ls -R dist/
        shell: bash

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}-${{ env.sha }}
          name: Release v${{ github.run_number }} (${{ env.sha }})
          files: dist/*
          body: |
            Automated release of Friendlai binaries.
            Commit: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
